"""add_social_fields

Revision ID: 026b6ad60406
Revises: 29a6bdd41bd5
Create Date: 2026-01-30 14:04:48.704456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '026b6ad60406'
down_revision: Union[str, None] = '29a6bdd41bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('qq', sa.String(length=20), nullable=True))
    op.add_column('admins', sa.Column('wechat', sa.String(length=50), nullable=True))
    op.add_column('admins', sa.Column('github', sa.String(length=100), nullable=True))
    op.add_column('admins', sa.Column('bilibili', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'bilibili')
    op.drop_column('admins', 'github')
    op.drop_column('admins', 'wechat')
    op.drop_column('admins', 'qq')
    # ### end Alembic commands ###
